#!/usr/bin/env bash

# First created: 
# Last modified: 2018 Jan 26

# Author: Feng Li
# email: fengggli@yahoo.com

# generated by kubespray
WOKER_NODE_PREFIX=fengggli-k8s-node-


all_nodes=($(kubectl get nodes -o jsonpath={.items[*].metadata.name}))
NR_ALL_NODES=${#all_nodes[*]}
NR_MASTER_NODES=1
NR_WORKER_NODES=$((NR_ALL_NODES-NR_MASTER_NODES))

env|grep NR_

for ((i=0;i<$NR_WORKER_NODES;i++))
do
echo setting for node ${i}}
#kubectl label nodes ${worker_nodes[i]}  minion-idx=${i}
kubectl label --overwrite nodes ${WORKER_NODE_PREFIX}fengggli-k8s-node-$((i+1))  minion-idx=${i}
done
