#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

runApplication surfaceFeatures

runApplication blockMesh
runApplication snappyHexMesh -overwrite

#runApplication mySimpleFoam -p port hostname
#runApplication mySimpleFoam localhost
runApplication mySimpleFoamCloud

#------------------------------------------------------------------------------
