apiVersion: v1
kind: Service
metadata:
  name: redis-master
  labels:
    app: redis
    role: master
    tier: backend
spec:
  type: NodePort
  ports:
  - port: 6379 # for access inside clouster
    nodePort: 30379  # for access from outside
    # targetPort: port inside the container
  selector:
    app: redis
    role: master
    tier: backend
